/**
 * ACTOR_IS_AGENT Comparator
 * Migration Plan v5.0 - Sprint 1, Task 1.3
 * 
 * Detects if PR is authored by an AI agent
 * Uses deterministic heuristics (not ML)
 */

import type { Comparator, ComparatorResult, PRContext } from '../types.js';
import { ComparatorId, FindingCode } from '../types.js';

const AGENT_AUTHOR_PATTERNS = [
  /copilot/i,
  /cursor/i,
  /augment/i,
  /codeium/i,
  /tabnine/i,
  /ai-/i,
  /bot-/i,
];

const COMMIT_MESSAGE_MARKERS = [
  'AI-generated',
  'Generated by',
  'Copilot',
  'Cursor',
  'Augment',
];

const LARGE_PR_THRESHOLD = 500;

export const actorIsAgentComparator: Comparator = {
  id: ComparatorId.ACTOR_IS_AGENT,
  version: '1.0.0',

  async evaluate(context: PRContext, params: any): Promise<ComparatorResult> {
    const signals: Array<{ type: string; matched: string; weight: number }> = [];

    // Heuristic 1: Author account patterns
    for (const pattern of AGENT_AUTHOR_PATTERNS) {
      if (pattern.test(context.author)) {
        signals.push({
          type: 'author_pattern',
          matched: context.author,
          weight: 0.50,
        });
        break;
      }
    }

    // Heuristic 2: Commit message markers
    for (const commit of context.commits) {
      for (const marker of COMMIT_MESSAGE_MARKERS) {
        if (commit.message.includes(marker)) {
          signals.push({
            type: 'commit_pattern',
            matched: marker,
            weight: 0.40,
          });
          break;
        }
      }
    }

    // Heuristic 3: PR size thresholds
    const totalChanges = context.additions + context.deletions;
    if (totalChanges > LARGE_PR_THRESHOLD) {
      signals.push({
        type: 'pr_size',
        matched: `${totalChanges} lines changed`,
        weight: 0.20,
      });
    }

    // Calculate confidence
    const totalWeight = signals.reduce((sum, s) => sum + s.weight, 0);
    const confidence = Math.min(1.0, totalWeight);
    const isAgentAuthored = confidence >= 0.50;

    if (isAgentAuthored) {
      return {
        comparatorId: this.id,
        status: 'pass',
        evidence: signals.map(s => ({
          type: 'commit',
          sha: '',
          message: `${s.type}: ${s.matched}`,
          author: context.author,
        })),
        reasonCode: FindingCode.AGENT_DETECTED,
        message: `Agent-authored PR detected (${(confidence * 100).toFixed(0)}% confidence)`,
      };
    }

    return {
      comparatorId: this.id,
      status: 'fail',
      evidence: [],
      reasonCode: FindingCode.PASS,
      message: `Not agent-authored (${(confidence * 100).toFixed(0)}% confidence)`,
    };
  },
};

