/**
 * Agent Summary Parser
 * Extracts intent and action traces from agent run summaries
 */

import type {
  Capability,
  ToolCall,
  FileChange,
  ExternalAction,
  AgentActionTrace,
} from '../../../types/agentGovernance.js';

export interface AgentRunSummary {
  agentId: string;
  agentVersion: string;
  toolCalls?: ToolCall[];
  filesModified?: FileChange[];
  externalActions?: ExternalAction[];
  summary?: string;
  requestedCapabilities?: Capability[];
}

/**
 * Extract agent identity from PR commit messages or comments
 * Looks for patterns like:
 * - "Generated by Cursor v1.2.3"
 * - "Co-authored-by: GitHub Copilot <copilot@github.com>"
 * - "Agent: replit-agent@v2.0.0"
 */
export function extractAgentIdentity(
  commits: Array<{ message: string; author: { name: string; email: string } }>,
  prBody: string
): { agentId: string; agentVersion: string } | null {
  // Check commit messages
  for (const commit of commits) {
    // Pattern: "Generated by <Agent> v<version>"
    const generatedByMatch = commit.message.match(/Generated by ([a-zA-Z-]+)\s+v?(\d+\.\d+\.\d+)/i);
    if (generatedByMatch) {
      return {
        agentId: generatedByMatch[1].toLowerCase(),
        agentVersion: generatedByMatch[2],
      };
    }
    
    // Pattern: "Co-authored-by: <Agent> <email>"
    const coAuthorMatch = commit.message.match(/Co-authored-by:\s*([^<]+)\s*<([^>]+)>/i);
    if (coAuthorMatch && coAuthorMatch[2].includes('copilot')) {
      return {
        agentId: 'copilot',
        agentVersion: 'unknown',
      };
    }
    
    // Pattern: "Agent: <agent-id>@v<version>"
    const agentMatch = commit.message.match(/Agent:\s*([a-zA-Z-]+)@v?(\d+\.\d+\.\d+)/i);
    if (agentMatch) {
      return {
        agentId: agentMatch[1].toLowerCase(),
        agentVersion: agentMatch[2],
      };
    }
  }
  
  // Check PR body
  const prAgentMatch = prBody.match(/(?:Generated|Created|Built) (?:by|with)\s+([a-zA-Z-]+)\s+v?(\d+\.\d+\.\d+)/i);
  if (prAgentMatch) {
    return {
      agentId: prAgentMatch[1].toLowerCase(),
      agentVersion: prAgentMatch[2],
    };
  }
  
  return null;
}

/**
 * Infer capabilities from file changes
 * Analyzes modified files to determine what capabilities were used
 */
export function inferCapabilitiesFromFileChanges(files: FileChange[]): Capability[] {
  const capabilities: Capability[] = [];
  
  for (const file of files) {
    const path = file.path.toLowerCase();
    
    // Database schema changes
    if (path.includes('schema.prisma') || path.includes('migrations/')) {
      capabilities.push({
        type: 'schema_modify',
        resource: file.path,
        scope: 'schema-change',
      });
    }
    
    // IAM/permissions changes
    if (path.includes('iam') || path.includes('permissions') || path.includes('policy.json')) {
      capabilities.push({
        type: 'iam_modify',
        resource: file.path,
        scope: 'permissions-change',
      });
    }
    
    // Infrastructure changes
    if (path.includes('terraform') || path.includes('cloudformation') || path.includes('infrastructure')) {
      if (file.changeType === 'created') {
        capabilities.push({
          type: 'infra_create',
          resource: file.path,
          scope: 'new-infrastructure',
        });
      } else {
        capabilities.push({
          type: 'infra_modify',
          resource: file.path,
          scope: 'infrastructure-change',
        });
      }
    }
    
    // API endpoint changes
    if (path.includes('routes') || path.includes('api') || path.includes('endpoints')) {
      capabilities.push({
        type: 'api_endpoint',
        resource: file.path,
        scope: 'api-change',
      });
    }
    
    // Deployment changes
    if (path.includes('dockerfile') || path.includes('deploy') || path.includes('k8s') || path.includes('kubernetes')) {
      capabilities.push({
        type: 'deployment_modify',
        resource: file.path,
        scope: 'deployment-change',
      });
    }
  }
  
  return capabilities;
}

/**
 * Parse agent run summary from PR comment or commit message
 * Looks for structured summaries in JSON or YAML format
 */
export function parseAgentRunSummary(text: string): AgentRunSummary | null {
  // Try to find JSON block
  const jsonMatch = text.match(/```json\n([\s\S]*?)```/);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[1]);
      if (parsed.agentId && parsed.agentVersion) {
        return parsed as AgentRunSummary;
      }
    } catch (error) {
      console.error('[agentSummaryParser] Failed to parse JSON:', error);
    }
  }
  
  return null;
}

/**
 * Build agent action trace from PR data
 */
export function buildAgentActionTrace(
  workspaceId: string,
  prNumber: number,
  repoFullName: string,
  agentIdentity: { agentId: string; agentVersion: string },
  files: FileChange[],
  toolCalls: ToolCall[] = [],
  externalActions: ExternalAction[] = []
): Omit<AgentActionTrace, 'id' | 'createdAt'> {
  return {
    workspaceId,
    prNumber,
    repoFullName,
    agentId: agentIdentity.agentId,
    agentVersion: agentIdentity.agentVersion,
    toolCalls,
    filesModified: files,
    externalActions,
    runtimeEffects: {},
  };
}

