/**
 * Agent Summary Parser
 * Extracts intent and action traces from agent run summaries
 */

import type {
  Capability,
  ToolCall,
  FileChange,
  ExternalAction,
  AgentActionTrace,
} from '../../../types/agentGovernance.js';

export interface AgentRunSummary {
  agentId: string;
  agentVersion: string;
  toolCalls?: ToolCall[];
  filesModified?: FileChange[];
  externalActions?: ExternalAction[];
  summary?: string;
  requestedCapabilities?: Capability[];
}

/**
 * Extract agent identity from PR commit messages or comments
 * Looks for patterns like:
 * - "Generated by Cursor v1.2.3"
 * - "Co-authored-by: GitHub Copilot <copilot@github.com>"
 * - "Agent: replit-agent@v2.0.0"
 */
export function extractAgentIdentity(
  commits: Array<{ message: string; author: { name: string; email: string } }>,
  prBody: string
): { agentId: string; agentVersion: string } | null {
  // Check commit messages
  for (const commit of commits) {
    // Pattern: "Generated by <Agent> v<version>"
    const generatedByMatch = commit.message.match(/Generated by ([a-zA-Z-]+)\s+v?(\d+\.\d+\.\d+)/i);
    if (generatedByMatch) {
      return {
        agentId: generatedByMatch[1].toLowerCase(),
        agentVersion: generatedByMatch[2],
      };
    }
    
    // Pattern: "Co-authored-by: <Agent> <email>"
    const coAuthorMatch = commit.message.match(/Co-authored-by:\s*([^<]+)\s*<([^>]+)>/i);
    if (coAuthorMatch && coAuthorMatch[2].includes('copilot')) {
      return {
        agentId: 'copilot',
        agentVersion: 'unknown',
      };
    }
    
    // Pattern: "Agent: <agent-id>@v<version>"
    const agentMatch = commit.message.match(/Agent:\s*([a-zA-Z-]+)@v?(\d+\.\d+\.\d+)/i);
    if (agentMatch) {
      return {
        agentId: agentMatch[1].toLowerCase(),
        agentVersion: agentMatch[2],
      };
    }
  }
  
  // Check PR body
  const prAgentMatch = prBody.match(/(?:Generated|Created|Built) (?:by|with)\s+([a-zA-Z-]+)\s+v?(\d+\.\d+\.\d+)/i);
  if (prAgentMatch) {
    return {
      agentId: prAgentMatch[1].toLowerCase(),
      agentVersion: prAgentMatch[2],
    };
  }
  
  return null;
}

/**
 * Infer capabilities from file changes
 * Analyzes modified files to determine what capabilities were used
 */
export function inferCapabilitiesFromFileChanges(files: FileChange[]): Capability[] {
  const capabilities: Capability[] = [];

  for (const file of files) {
    const path = file.path.toLowerCase();

    // Database schema changes → schema_modify
    if (path.includes('schema.prisma') || path.includes('migrations/')) {
      capabilities.push({ type: 'schema_modify', resource: file.path, scope: 'schema-change' });
    }

    // ORM model / repository / DAO files that perform writes → db_write
    if (
      path.includes('repository') || path.includes('dao') ||
      (path.includes('model') && (path.endsWith('.ts') || path.endsWith('.js') || path.endsWith('.py'))) ||
      path.includes('mutation') || path.includes('write')
    ) {
      capabilities.push({ type: 'db_write', resource: file.path, scope: 'database-write' });
    }

    // Query / read files → db_read
    if (path.includes('query') || path.includes('reader') || path.includes('fetch') || path.includes('finder')) {
      capabilities.push({ type: 'db_read', resource: file.path, scope: 'database-read' });
    }

    // IAM / permissions changes → iam_modify
    if (path.includes('iam') || path.includes('permissions') || path.includes('policy.json') || path.includes('rbac') || path.includes('acl')) {
      capabilities.push({ type: 'iam_modify', resource: file.path, scope: 'permissions-change' });
    }

    // Infrastructure changes → infra_create / infra_modify / infra_delete
    if (path.includes('terraform') || path.includes('.tf') || path.includes('cloudformation') || path.includes('infrastructure') || path.includes('pulumi')) {
      if (file.changeType === 'created') {
        capabilities.push({ type: 'infra_create', resource: file.path, scope: 'new-infrastructure' });
      } else if (file.changeType === 'deleted') {
        capabilities.push({ type: 'infra_delete', resource: file.path, scope: 'infrastructure-removal' });
      } else {
        capabilities.push({ type: 'infra_modify', resource: file.path, scope: 'infrastructure-change' });
      }
    }

    // S3 / blob storage / object storage → s3_read / s3_write / s3_delete
    if (path.includes('s3') || path.includes('storage') || path.includes('bucket') || path.includes('blob') || path.includes('gcs') || path.includes('minio')) {
      if (path.includes('delete') || path.includes('remove') || path.includes('purge')) {
        capabilities.push({ type: 's3_delete', resource: file.path, scope: 'storage-delete' });
      } else if (path.includes('upload') || path.includes('put') || path.includes('write') || path.includes('store')) {
        capabilities.push({ type: 's3_write', resource: file.path, scope: 'storage-write' });
      } else {
        capabilities.push({ type: 's3_read', resource: file.path, scope: 'storage-read' });
      }
    }

    // Secret / credential / vault files → secret_read / secret_write
    if (
      path.includes('secret') || path.includes('vault') || path.includes('credential') ||
      path.includes('.env') || path.includes('keystore') || path.includes('ssm')
    ) {
      if (path.includes('write') || path.includes('store') || path.includes('create') || file.changeType === 'created') {
        capabilities.push({ type: 'secret_write', resource: file.path, scope: 'secret-write' });
      } else {
        capabilities.push({ type: 'secret_read', resource: file.path, scope: 'secret-read' });
      }
    }

    // Public network exposure → network_public
    if (
      path.includes('ingress') || path.includes('loadbalancer') || path.includes('load-balancer') ||
      path.includes('public') || path.includes('cdn') || path.includes('cloudfront') ||
      path.includes('api-gateway') || path.includes('nginx.conf')
    ) {
      capabilities.push({ type: 'network_public', resource: file.path, scope: 'public-network' });
    }

    // Internal / VPC / private networking → network_private
    if (path.includes('vpc') || path.includes('private-subnet') || path.includes('service-mesh') || path.includes('istio')) {
      capabilities.push({ type: 'network_private', resource: file.path, scope: 'private-network' });
    }

    // API route/endpoint files (narrowed to avoid catching every file with 'api' in its path)
    if (path.includes('/routes/') || path.includes('/endpoints/') || path.includes('/controllers/') || path.match(/\/api\/[a-z]/)) {
      capabilities.push({ type: 'api_endpoint', resource: file.path, scope: 'api-change' });
    }

    // Deployment changes → deployment_modify
    if (
      path.includes('dockerfile') || path.includes('docker-compose') ||
      path.includes('/deploy/') || path.includes('k8s/') || path.includes('kubernetes/') ||
      path.includes('helm/') || path.includes('.github/workflows/')
    ) {
      capabilities.push({ type: 'deployment_modify', resource: file.path, scope: 'deployment-change' });
    }
  }

  return capabilities;
}

/**
 * Parse agent run summary from PR comment or commit message
 * Looks for structured summaries in JSON or YAML format
 */
export function parseAgentRunSummary(text: string): AgentRunSummary | null {
  // Try to find JSON block
  const jsonMatch = text.match(/```json\n([\s\S]*?)```/);
  if (jsonMatch) {
    try {
      const parsed = JSON.parse(jsonMatch[1]);
      if (parsed.agentId && parsed.agentVersion) {
        return parsed as AgentRunSummary;
      }
    } catch (error) {
      console.error('[agentSummaryParser] Failed to parse JSON:', error);
    }
  }
  
  return null;
}

/**
 * Build agent action trace from PR data
 */
export function buildAgentActionTrace(
  workspaceId: string,
  prNumber: number,
  repoFullName: string,
  agentIdentity: { agentId: string; agentVersion: string },
  files: FileChange[],
  toolCalls: ToolCall[] = [],
  externalActions: ExternalAction[] = []
): Omit<AgentActionTrace, 'id' | 'createdAt'> {
  return {
    workspaceId,
    prNumber,
    repoFullName,
    agentId: agentIdentity.agentId,
    agentVersion: agentIdentity.agentVersion,
    toolCalls,
    filesModified: files,
    externalActions,
    runtimeEffects: [],
  };
}

