/**
 * Agent PR Detection Heuristics
 * 
 * Detects if a PR is likely authored by an AI agent/LLM tool
 * Uses deterministic heuristics (no ML):
 * - Author account patterns
 * - Commit message markers
 * - PR size thresholds
 * - Tool signatures in code
 */

export interface AgentDetectionResult {
  isAgentAuthored: boolean;
  confidence: number;
  signals: AgentSignal[];
}

export interface AgentSignal {
  type: 'author_pattern' | 'commit_pattern' | 'pr_size' | 'tool_signature';
  matched: string;
  weight: number;
}

export interface PRContext {
  author: string;
  commits: Array<{ message: string; author: string }>;
  additions: number;
  deletions: number;
  files: Array<{ filename: string; patch?: string }>;
}

/**
 * Agent author patterns
 * Matches common AI tool account names
 */
const AGENT_AUTHOR_PATTERNS = [
  /copilot/i,
  /claude/i,
  /gpt/i,
  /chatgpt/i,
  /ai-/i,
  /\bbot\b/i,
  /assistant/i,
  /codewhisperer/i,
  /tabnine/i,
  /cursor/i,
  /aider/i,
  /augment/i,
];

/**
 * Commit message markers
 * Patterns that indicate AI-generated commits
 */
const COMMIT_MESSAGE_MARKERS = [
  'Co-authored-by: GitHub Copilot',
  'Co-authored-by: Claude',
  'Generated by Claude',
  'Generated by ChatGPT',
  'AI-generated',
  'Automated commit',
  'Co-Authored-By: AI',
  '[bot]',
  '[ai]',
];

/**
 * Tool signatures in code
 * Patterns in code that indicate AI generation
 */
const TOOL_SIGNATURE_PATTERNS = [
  /\/\/ Generated by/i,
  /# Auto-generated/i,
  /@generated/i,
  /\/\* AI-generated \*\//i,
  /# Created by AI/i,
];

/**
 * PR size threshold
 * Large PRs (>1000 lines) are more suspicious for agent authorship
 */
const LARGE_PR_THRESHOLD = 1000;

/**
 * Detect if a PR is likely authored by an AI agent
 */
export function detectAgentAuthoredPR(pr: PRContext): AgentDetectionResult {
  const signals: AgentSignal[] = [];
  
  // Heuristic 1: Author account patterns
  for (const pattern of AGENT_AUTHOR_PATTERNS) {
    if (pattern.test(pr.author)) {
      signals.push({
        type: 'author_pattern',
        matched: pr.author,
        weight: 0.50,
      });
      break; // Only count once
    }
  }
  
  // Heuristic 2: Commit message markers
  for (const commit of pr.commits) {
    for (const marker of COMMIT_MESSAGE_MARKERS) {
      if (commit.message.includes(marker)) {
        signals.push({
          type: 'commit_pattern',
          matched: marker,
          weight: 0.40,
        });
        break; // Only count first match per commit
      }
    }
  }
  
  // Heuristic 3: PR size thresholds
  const totalChanges = pr.additions + pr.deletions;
  if (totalChanges > LARGE_PR_THRESHOLD) {
    signals.push({
      type: 'pr_size',
      matched: `${totalChanges} lines changed`,
      weight: 0.20,
    });
  }
  
  // Heuristic 4: Tool signatures in code
  const filesWithSignatures = new Set<string>();
  for (const file of pr.files) {
    if (!file.patch) continue;
    
    for (const signature of TOOL_SIGNATURE_PATTERNS) {
      if (signature.test(file.patch)) {
        filesWithSignatures.add(file.filename);
        break;
      }
    }
  }
  
  if (filesWithSignatures.size > 0) {
    signals.push({
      type: 'tool_signature',
      matched: `${filesWithSignatures.size} file(s) with tool signatures`,
      weight: 0.30,
    });
  }
  
  // Calculate confidence (sum of weights, capped at 1.0)
  const totalWeight = signals.reduce((sum, s) => sum + s.weight, 0);
  const confidence = Math.min(1.0, totalWeight);
  
  // Consider agent-authored if confidence >= 50%
  const isAgentAuthored = confidence >= 0.50;
  
  return { isAgentAuthored, confidence, signals };
}

