# ======================================================================
# Template A7: SBOM & CVE Enforcement
# ======================================================================
# 
# Purpose: Block PRs with critical CVEs or non-compliant licenses
# Use Case: Organizations that need to enforce security and compliance
#           policies on dependencies
# 
# This pack:
# - Blocks PRs with critical CVEs in dependencies
# - Warns about high-severity CVEs
# - Blocks non-compliant licenses (GPL, AGPL, etc.)
# - Tracks dependency changes
# 
# Phase 3C.1 - SBOM/CVE Facts
# ======================================================================

apiVersion: verta.ai/v1
kind: PolicyPack
metadata:
  id: sbom-cve-enforcement
  name: SBOM & CVE Enforcement
  version: 1.0.0
  description: Block PRs with critical CVEs or non-compliant licenses
  author: Verta AI
  tags:
    - sbom
    - security
    - cve
    - license-compliance
    - dependencies

scope:
  type: workspace
  branches:
    include:
      - main
      - master
      - release/*
      - production

rules:
  # Rule 1: Block critical CVEs
  - id: block-critical-cves
    name: Block Critical CVEs
    description: Block PRs that introduce packages with critical CVEs
    enabled: true
    
    trigger:
      anyChangedPaths:
        - "**/*.sbom.json"
        - "**/*.spdx.json"
        - "**/*.cyclonedx.json"
        - "**/sbom.json"
        - "**/bom.json"
    
    obligations:
      - condition:
          fact: sbom.cves.critical.count
          operator: ">"
          value: 0
        severity: critical
        decisionOnFail: block
        message: |
          Critical CVEs detected in dependencies.
          
          This PR introduces or contains packages with critical security vulnerabilities.
          
          Please:
          1. Review the CVEs listed in the SBOM
          2. Update affected packages to patched versions
          3. If no patch is available, consider alternative packages
          4. Document any accepted risks with security team approval
          
          Security policy requires zero critical CVEs in production dependencies.

  # Rule 2: Warn on high-severity CVEs
  - id: warn-high-cves
    name: Warn on High CVEs
    description: Warn when high-severity CVEs are detected
    enabled: true
    
    trigger:
      anyChangedPaths:
        - "**/*.sbom.json"
        - "**/*.spdx.json"
        - "**/*.cyclonedx.json"
        - "**/sbom.json"
    
    obligations:
      - condition:
          fact: sbom.cves.high.count
          operator: ">"
          value: 0
        severity: high
        decisionOnFail: warn
        message: |
          High-severity CVEs detected in dependencies.
          
          Please review and consider updating affected packages.
          
          While not blocking, high-severity CVEs should be addressed promptly.

  # Rule 3: Block non-compliant licenses
  - id: block-non-compliant-licenses
    name: Block Non-Compliant Licenses
    description: Block packages with non-approved licenses
    enabled: true
    
    trigger:
      anyChangedPaths:
        - "**/*.sbom.json"
        - "**/*.spdx.json"
        - "**/*.cyclonedx.json"
        - "**/sbom.json"
    
    obligations:
      - condition:
          fact: sbom.licenses.nonCompliant
          operator: "!="
          value: []
        severity: high
        decisionOnFail: block
        message: |
          Non-compliant licenses detected in dependencies.
          
          The following licenses are not approved for use:
          {sbom.licenses.nonCompliant}
          
          Approved licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC
          
          Please:
          1. Replace packages with non-compliant licenses
          2. Or request license exception from legal team
          
          Copyleft licenses (GPL, AGPL, LGPL) require legal review.

  # Rule 4: Notify on dependency changes
  - id: notify-dependency-changes
    name: Notify on Dependency Changes
    description: Notify when dependencies are added or removed
    enabled: true
    
    trigger:
      anyChangedPaths:
        - "**/*.sbom.json"
        - "**/*.spdx.json"
        - "**/*.cyclonedx.json"
        - "**/sbom.json"
    
    obligations:
      - condition:
          or:
            - fact: sbom.packages.added.count
              operator: ">"
              value: 0
            - fact: sbom.packages.removed.count
              operator: ">"
              value: 0
        severity: low
        decisionOnFail: pass
        message: |
          Dependency changes detected.
          
          Packages added: {sbom.packages.added.count}
          Packages removed: {sbom.packages.removed.count}
          
          Please ensure SBOM is up-to-date and all changes are intentional.

evaluation:
  externalDependencyMode: soft_fail
  unknownArtifactMode: soft_fail
  budgets:
    totalTimeoutSeconds: 60
    perComparatorTimeoutSeconds: 15
    maxApiCalls: 30
  maxFindings: 50
  maxEvidenceSnippetsPerFinding: 3

